### ISSUE TITLE
Generating co-regulation score matrices

### ISSUE THREAD

**Issue by opain** [ksiewert/GCSC#1]
Hello,

Thank you for developing this exciting method for TWAS-based enrichment analysis.

Would you be able to provide instructions/code for creating co-regulation score matrices for other gene expression panels? For example, I would like to generate the matrices based on the PsychENCODE DLPFC data which I have in FUSION format.

Apologies, if this information is already available.

Many thanks,

Ollie

**Comment by ksiewert** [comment]
This is a great question (and something I've been planning to provide instructions for). I'm on maternity leave, so things will be a bit delayed, but I'll try to get instructions up on how to do this in the next couple of weeks.

 In brief, you can impute expression into 1000 genomes EUR individuals (or some other reference panel) using plink, compute correlations in imputed expression between genes, set the correlations of each gene with itself to the bias-corrected amount, sum co-regulation across genes to get co-regulation scores, and finally apply tissue standardization. I know this may be a lot though, so I'll provide some code samples when I have more time.

**Comment by opain** [comment]
Thank you for your reply. Congrats on maternity! Please no rush to reply.

Your description of the process is useful. Thank you. Potentially of interest, I have written some code for predicting expression from FUSION weights into genotype datasets such as 1000 Genomes: https://github.com/opain/Predicting-TWAS-features.

I can see you provided further detail regarding the correlation matrix and correction in the paper. I think I can create the co-regulation scores matrices based on this information. However, my familiarity with python is poor so may struggle to get the matrix in the right format. I will let you know if I make any progress and keep an eye out for any updates to your repo.

Many thanks,

Ollie

**Comment by ksiewert** [comment]
Hi Ollie, I wanted to let you know a while back I added some more detailed instructions on how to do this to the wiki. Unfortunately, I don't think I have time to flush it out anymore.  Hope this at least a little help though.

**Comment by opain** [comment]
Ah, yes. That is very useful. Many thanks for adding that documentation. It looks quite clear. I will have a go.
