### ISSUE TITLE
--tissues flag

### ISSUE THREAD

**Issue by opain** [ksiewert/GCSC#2]
Hello,

I have a small issue. Perhaps my set up isn't quite right, but it seems the --tissues flag is required for GCSC to find the files for concatenation. 

Here is screenshot of my TWAS results files:
![image](https://user-images.githubusercontent.com/43761992/186225790-ef49c889-020e-41f1-b9ff-c28764fecc44.png)

When I run GCSC without the --tissues flag I get an error, like this:
![image](https://user-images.githubusercontent.com/43761992/186226054-e7224f8b-336a-45e3-ad51-241aa323bb0a.png)

However, GCSC works when I specify the tissues present (--tissues Adipose_Subcutaneous Brain_Hippocampus). From my reading of the wiki, I expected GCSC to detect the tissues available?

Many thanks,

Ollie

**Comment by ksiewert** [comment]
Hi Ollie. GCSC should automatically detect tissues, but it uses the co-regulation score files to detect them (these files should end in coregscores.npz). If you could screenshot what that directory looks like, that would be helpful.

**Comment by opain** [comment]
Dear Katie,

Thank you for your reply. Ah, that explains it, as I had all the coregulation score files in the directory. Apologies for the misunderstanding. I assumed that GCSC would detect tissues based on the TWAS rather than the coregulation score file directory. I downloaded all coregulation score files so I can use GCSC on a range of TWAS with different tissues included. Not a problem though as I will just specify the tissues that I want to be included for each run of GCSC. 

Many thanks,

Ollie
